### ISSUE TITLE
Inappropriate description

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/ckeditor_addon#1]
> Backdrop 1.2 has jailed CKEditor in core, with critical bugs, reduced functionality, and loss of customization possibility.

A reminder that this is an early community project being built by working people on their own time. There is no need to advertise current weaknesses like this, especially when there are open issues acknowledging that there are problems waiting to be fixed. I would recommend you stick to the issue queues to describe problems with the software, and more importantly, be civil about it.

**Comment by klonos** [comment]
I agree with @docwilmot 

May I suggest the following:
- A better, less generic module name. I was thinking to deprecate this in favor of a "CKEditor Extras" module. Even if features that this module offers eventually make into core, it will still be useful as a place where people can request that some things are added here first. Think of it as a "testing ground" of CKEditor features that we are not yet ready to or sure if we need to put in core but that are in "popular demand".
- Provide a settings page with each feature/addition/fix as a separate checkbox. This way people can enable only the features they need.

**Comment by klonos** [comment]
FTR: While this module ships with 4.5.5 and has not been updated since April 2016, CKEditor has been updated in Backdrop core to:

- 4.5.9, with https://github.com/backdrop/backdrop-issues/issues/1560 in Backdrop 1.4.0 (May. 2016)
- 4.6.0, with https://github.com/backdrop/backdrop-issues/issues/2463 in Backdrop 1.6.0 (Jan. 2017)
- 4.7.2, with https://github.com/backdrop/backdrop-issues/issues/2799 in Backdrop 1.8.0 (Sep. 2017)
- 4.7.3 (+ security update), with https://github.com/backdrop/backdrop/commit/bb7aa35af0dda02c4ea6f9f1b35f45de450b2d80, in Backdrop 1.9.4 (April 2018)
- 4.11.1, with https://github.com/backdrop/backdrop-issues/issues/3355 in Backdrop v1.12.0 (Jan. 2019)

We are currently in 4.14.0 with https://github.com/backdrop/backdrop-issues/issues/3355 since Backdrop 1.15.1 (March 2020).

I suggest to delete or archive this project.

**Comment by jenlampton** [comment]
This project does still include some features that are missing from core. Since there are no releases, I don't think it's necessary to archive or delete it, but we **put's on bug-squad hat** should at least add a notice to the README about the security vulnerability.

**Comment by jenlampton** [comment]
I have updated the modified the description as follows:

```
This project contains enhancements to the Backdrop core CKEditor integration, and serves as a template for customizing CKEditor integration.
```
