### ISSUE TITLE
How to use default Moono skin?

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/ckeditor_addon#5]
Thank you for your module!
All enhancements are very useful. The only think I want to alter is Ckeditor skin. How can I set Moono skin as default?

**Comment by ghost** [comment]
Since CKEditor 4, you cannot assemble the ckeditor manually from parts : you have to use the ckeditor builder, either as part of the github dev repository : https://github.com/ckeditor/ckeditor-dev, or from ckeditor site — if you ask, we will use the later…

Visit http://ckeditor.com/builder

Click, at top right, the "Upload build-config.js" button
Navigate to `ckeditor_addon/js/ckeditor/build-config.js`
"my" configuration will show

Scroll down until "Available skins", select the one you want
While you are at it, select the language(s) you wish to provide to your users

Click download..
Extract and replace the ckeditor folder
Done

Notes : 
You may probably add any plugin you like, but you may have to add some elements in the ckeditor_addon.module if the plugin has a button which will have to be added to the toolbar
This is NOT automatic !
You will also have to provide a specific icon in the `ckeditor_addon/image/buttons` folder, just for the ckeditor settings form...
You can track the "Save" plugin integration as an example

Be carefull NOT to add the link plugin : it would conflict with the backdroplink plugin.

Enjoy !

**Comment by Al-Rozhkov** [comment]
Thank you for such a detailed answer!
Indeed your module is a good example of how to customize Ckeditor in Backdrop.
Thanks again!

**Comment by jenlampton** [comment]
Looks like this question was answered, closing issue.
